
package webservice;

import jakarta.xml.ws.WebFault;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.0
 * Generated source version: 3.0
 * 
 */
@WebFault(name = "CategoriaRepetidaException", targetNamespace = "http://WebService/")
public class CategoriaRepetidaException_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private CategoriaRepetidaException faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public CategoriaRepetidaException_Exception(String message, CategoriaRepetidaException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param cause
     * @param faultInfo
     * @param message
     */
    public CategoriaRepetidaException_Exception(String message, CategoriaRepetidaException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: webservice.CategoriaRepetidaException
     */
    public CategoriaRepetidaException getFaultInfo() {
        return faultInfo;
    }

}
