
package webservice;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.jws.soap.SOAPBinding;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.Action;
import jakarta.xml.ws.FaultAction;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.0
 * Generated source version: 3.0
 * 
 */
@WebService(name = "Publicador", targetNamespace = "http://WebService/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Publicador {


	/**
     * 
     * @param arg0
     * @param arg1
     * @return
     *     returns webservice.EstadoError
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://WebService/Publicador/iniciarSesionRequest", output = "http://WebService/Publicador/iniciarSesionResponse")
    public EstadoError iniciarSesion(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1);
    
    /**
     * 
     * @return
     *     returns webservice.DtProveedor
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://WebService/Publicador/getDTProveedorRequest", output = "http://WebService/Publicador/getDTProveedorResponse")
    public DtProveedor getDTProveedor();
    
    /**
     * 
     * @return
     *     returns webservice.DtTurista
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://WebService/Publicador/getDTTuristaRequest", output = "http://WebService/Publicador/getDTTuristaResponse")
    public DtTurista getDTTurista();
   
    /**
     * 
     * @return
     *     returns webservice.SetString
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://WebService/Publicador/listarDepartamentosRequest", output = "http://WebService/Publicador/listarDepartamentosResponse")
    public SetString listarDepartamentos();
    
    /**
     * 
     * @return
     *     returns webservice.SetString
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://WebService/Publicador/listarCategoriasRequest", output = "http://WebService/Publicador/listarCategoriasResponse")
    public SetString listarCategorias();
    
    /**
     * 
     * @param arg0
     * @param arg1
     * @return
     *     returns webservice.SetDTActividadTuristica
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://WebService/Publicador/listarActividadesDeptoYCateRequest", output = "http://WebService/Publicador/listarActividadesDeptoYCateResponse")
    public SetDTActividadTuristica listarActividadesDeptoYCate(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1);

}
